CREATE TABLE works(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    publishing_company VARCHAR(155) DEFAULT 'unknown',
    photo VARCHAR(255) NOT NULL,
    authors VARCHAR(155) DEFAULT 'unknown',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);